[package]
name = "muco"
version = "0.1.0"
authors = ["Aurabindo J <mail@aurabindo.in>"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
clap = "2.31"
